<?php
/**
 * @var $user array|null
 * @var $error string|null
 */
?>
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8"/>
        <title>Login</title>
        <link href='//fonts.googleapis.com/css?family=Lato:300' rel='stylesheet' type='text/css'>
        <link href='/main.css' rel='stylesheet' type='text/css'>
    </head>
    <body class="login">
        <h3>Secure auth</h3>

        <form method="POST" action="/login">
            <table>
                <tr>
                    <td>
                        <label for="login">Login</label>
                    </td>
                    <td>
                        <input id="login" name="login" type="text">
                    </td>
                </tr>
                <tr>
                    <td>
                        <label for="password">Password</label>
                    </td>
                    <td>
                        <input id="password" type="password" name="password">
                    </td>
                </tr>
                <tr>
                    <td>
                    </td>
                    <td>
                        <input type="submit">
                    </td>
                </tr>
            </table>
            <span class="error"><?php echo $error;?></span>
        </form>
    </body>
</html>
